lint:
	go mod tidy
	go fmt ./...
	go vet ./...
	golangci-lint run ./...

pb:
	protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative example/pb/*.proto
	frgen pbfinger --in=example/pb/hello.proto
