// Code generated by frgen , DO NOT EDIT.
package pb

import (
	"github.com/pinealctx/neptune/mpb"
	"google.golang.org/protobuf/proto"
)

const (
	// FpPbHello crc32.ChecksumIEEE([]byte("pb.Hello")) -653391380
	FpPbHello = uint32(0xd90e09ec)
)

func (*Hello) Fingerprint() uint32 {
	return FpPbHello
}

// init function to register generated proto message generator functions
func init() {
	mpb.RegisterGenerator(func() proto.Message { return &Hello{} })
}
