// Code generated by frgen , DO NOT EDIT.
package pb

import (
	"github.com/pinealctx/neptune/mpb"
	"google.golang.org/protobuf/proto"
)

const ()

// init function to register generated proto message generator functions
func init() {
}
